---
- hosts: all
  gather_facts: false
  become: true
  serial: 1
  any_errors_fatal: yes
  tasks:
  - name: Apply updates using dnf module.
    dnf:
      name: '*'
      state: latest
      update_cache: true
      update_only: true
    register: dnfupdate_status

  - name: Remove packages not needed anymore
    dnf:
      autoremove: true

  - name: Reboot when packages were updated
    reboot:
      post_reboot_delay: 60
    when: apt_update_status.changed